name: Deploy to Test Environment

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to test.werdu.de
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Sync files to test server
      uses: SamKirsch/ftp-deploy-action@v4.3.4
      with:
        server: ${{ secrets.TEST_FTP_SERVER }}
        username: ${{ secrets.TEST_FTP_USERNAME }}
        password: ${{ secrets.TEST_FTP_PASSWORD }}
        server-dir: /
